/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {
double firstNumber = 0;
double secondNumber = 0;
double result = 0;
char characterOpreration;
String operations;
private Object math;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtextDisplay = new javax.swing.JTextField();
        jbutton8 = new javax.swing.JButton();
        jbutton9 = new javax.swing.JButton();
        jbutton7 = new javax.swing.JButton();
        jbutton4 = new javax.swing.JButton();
        jbutton5 = new javax.swing.JButton();
        jbutton6 = new javax.swing.JButton();
        jbuttonPi = new javax.swing.JButton();
        jbutton1 = new javax.swing.JButton();
        jbutton2 = new javax.swing.JButton();
        jbutton3 = new javax.swing.JButton();
        jbtnDivision = new javax.swing.JButton();
        jbutton0 = new javax.swing.JButton();
        jbuttonDot = new javax.swing.JButton();
        jbuttonPlusMinus = new javax.swing.JButton();
        jbuttonEqual = new javax.swing.JButton();
        jbuttonMultiplication = new javax.swing.JButton();
        jbuttonBackspace = new javax.swing.JButton();
        jbuttonClear = new javax.swing.JButton();
        jbuttonRoot = new javax.swing.JButton();
        jbuttonPlus = new javax.swing.JButton();
        jbuttonlog = new javax.swing.JButton();
        jbuttonRandomNumber = new javax.swing.JButton();
        jbuttonXSquared2 = new javax.swing.JButton();
        jbuttonXSquared3 = new javax.swing.JButton();
        jbuttonSinh = new javax.swing.JButton();
        jbuttonXSquaredY = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jbuttonTan = new javax.swing.JButton();
        jbuttonCbr = new javax.swing.JButton();
        jbuttonTanh = new javax.swing.JButton();
        jbuttonSin = new javax.swing.JButton();
        jbuttonSubtract = new javax.swing.JButton();
        jbuttonCos = new javax.swing.JButton();
        jbuttonBinary = new javax.swing.JButton();
        jbuttonOctal = new javax.swing.JButton();
        jbuttonCosh = new javax.swing.JButton();
        jbuttonHexaDecimal = new javax.swing.JButton();
        jbuttonFactorial = new javax.swing.JButton();
        jbuttonModulus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtextDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtextDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextDisplayActionPerformed(evt);
            }
        });

        jbutton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton8.setText("8");
        jbutton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton8ActionPerformed(evt);
            }
        });

        jbutton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton9.setText("9");
        jbutton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton9ActionPerformed(evt);
            }
        });

        jbutton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton7.setText("7");
        jbutton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton7ActionPerformed(evt);
            }
        });

        jbutton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton4.setText("4");
        jbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton4ActionPerformed(evt);
            }
        });

        jbutton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton5.setText("5");
        jbutton5.setActionCommand("");
        jbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton5ActionPerformed(evt);
            }
        });

        jbutton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton6.setText("6");
        jbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton6ActionPerformed(evt);
            }
        });

        jbuttonPi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonPi.setText("π ");
        jbuttonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonPiActionPerformed(evt);
            }
        });

        jbutton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton1.setText("1");
        jbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton1ActionPerformed(evt);
            }
        });

        jbutton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton2.setText("2");
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton2ActionPerformed(evt);
            }
        });

        jbutton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton3.setText("3");
        jbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton3ActionPerformed(evt);
            }
        });

        jbtnDivision.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnDivision.setText("/");
        jbtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivisionActionPerformed(evt);
            }
        });

        jbutton0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton0.setText("0");
        jbutton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton0ActionPerformed(evt);
            }
        });

        jbuttonDot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonDot.setText(".");
        jbuttonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonDotActionPerformed(evt);
            }
        });

        jbuttonPlusMinus.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbuttonPlusMinus.setText("±");
        jbuttonPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonPlusMinusActionPerformed(evt);
            }
        });

        jbuttonEqual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonEqual.setText("=");
        jbuttonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonEqualActionPerformed(evt);
            }
        });

        jbuttonMultiplication.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonMultiplication.setText("*");
        jbuttonMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMultiplicationActionPerformed(evt);
            }
        });

        jbuttonBackspace.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonBackspace.setText("<-");
        jbuttonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonBackspaceActionPerformed(evt);
            }
        });

        jbuttonClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonClear.setText("C");
        jbuttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonClearActionPerformed(evt);
            }
        });

        jbuttonRoot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonRoot.setText("√");
        jbuttonRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonRootActionPerformed(evt);
            }
        });

        jbuttonPlus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonPlus.setText("+");
        jbuttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonPlusActionPerformed(evt);
            }
        });

        jbuttonlog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonlog.setText("Log");
        jbuttonlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonlogActionPerformed(evt);
            }
        });

        jbuttonRandomNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonRandomNumber.setText("Rund");
        jbuttonRandomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonRandomNumberActionPerformed(evt);
            }
        });

        jbuttonXSquared2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonXSquared2.setText("x^2");
        jbuttonXSquared2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonXSquared2ActionPerformed(evt);
            }
        });

        jbuttonXSquared3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonXSquared3.setText("x^3");
        jbuttonXSquared3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonXSquared3ActionPerformed(evt);
            }
        });

        jbuttonSinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonSinh.setText("Sinh");
        jbuttonSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSinhActionPerformed(evt);
            }
        });

        jbuttonXSquaredY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonXSquaredY.setText("x^y");
        jbuttonXSquaredY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonXSquaredYActionPerformed(evt);
            }
        });

        jButton27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton27.setText("+");

        jbuttonTan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonTan.setText("Tan");
        jbuttonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonTanActionPerformed(evt);
            }
        });

        jbuttonCbr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonCbr.setText("Cbr");
        jbuttonCbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCbrActionPerformed(evt);
            }
        });

        jbuttonTanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonTanh.setText("Tanh");
        jbuttonTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonTanhActionPerformed(evt);
            }
        });

        jbuttonSin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonSin.setText("Sin");
        jbuttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSinActionPerformed(evt);
            }
        });

        jbuttonSubtract.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonSubtract.setText("-");
        jbuttonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSubtractActionPerformed(evt);
            }
        });

        jbuttonCos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonCos.setText("Cos");
        jbuttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCosActionPerformed(evt);
            }
        });

        jbuttonBinary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonBinary.setText("BIN");
        jbuttonBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonBinaryActionPerformed(evt);
            }
        });

        jbuttonOctal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonOctal.setText("OCT");
        jbuttonOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonOctalActionPerformed(evt);
            }
        });

        jbuttonCosh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonCosh.setText("Cosh");
        jbuttonCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCoshActionPerformed(evt);
            }
        });

        jbuttonHexaDecimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonHexaDecimal.setText("Hexa");
        jbuttonHexaDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonHexaDecimalActionPerformed(evt);
            }
        });

        jbuttonFactorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonFactorial.setText("!");
        jbuttonFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonFactorialActionPerformed(evt);
            }
        });

        jbuttonModulus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbuttonModulus.setText("Mod");
        jbuttonModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonModulusActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Programming");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtextDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbuttonXSquared2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbuttonCbr))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbuttonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbuttonXSquaredY)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbuttonTan)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbuttonCosh)
                                    .addComponent(jbuttonModulus)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jbutton0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbuttonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jbuttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jbuttonPi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbuttonCos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbuttonSinh))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jbuttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(jbuttonXSquared3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbuttonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbuttonTanh)
                                            .addComponent(jbuttonRandomNumber)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jbuttonlog)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbuttonSin))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbuttonBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbuttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbuttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbuttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuttonOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonHexaDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(396, Short.MAX_VALUE)
                    .addComponent(jButton27)
                    .addContainerGap(397, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtextDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbuttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbuttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jbuttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbuttonPi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbuttonSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbuttonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jbuttonXSquaredY, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbuttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbuttonModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbuttonTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbuttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbuttonlog, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbutton0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbuttonCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonXSquared2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbuttonRandomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonXSquared3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbuttonOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbuttonHexaDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbuttonBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(226, Short.MAX_VALUE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(148, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Positions of the curly brackets after ActionPerformed() method can not
     * be changed since they are auto-fixed 
     */
    
    /*
     * The calculation of the trigonometric functions such as sin,cos,tan,sinh,
     * cosh,tanh will be in radians
     */
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(250, 420);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(250, 420);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(450, 400);
        jtextDisplay.setSize(600, 900);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbuttonRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonRootActionPerformed
        double operations = Double.parseDouble(String.valueOf
        (jtextDisplay.getText()));
        operations = Math.sqrt(operations);
        jtextDisplay.setText(String.valueOf(operations));
    
    }//GEN-LAST:event_jbuttonRootActionPerformed

    private void jtextDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextDisplayActionPerformed

    private void jbutton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton7ActionPerformed
        // TODO add your handling code here:
    String iNumber = jtextDisplay.getText() + jbutton7.getText();
    jtextDisplay.setText(iNumber);
            
    }//GEN-LAST:event_jbutton7ActionPerformed

    private void jbutton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton8ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton8.getText();
    jtextDisplay.setText(iNumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton8ActionPerformed

    private void jbutton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton9ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton9.getText();
    jtextDisplay.setText(iNumber);
    }//GEN-LAST:event_jbutton9ActionPerformed

    private void jbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton4ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton4.getText();
    jtextDisplay.setText(iNumber);
    }//GEN-LAST:event_jbutton4ActionPerformed

    private void jbuttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonClearActionPerformed
    jtextDisplay.setText("");
    }//GEN-LAST:event_jbuttonClearActionPerformed

    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton1ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton1.getText();
    jtextDisplay.setText(iNumber);

    }//GEN-LAST:event_jbutton1ActionPerformed

    private void jbutton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton0ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton0.getText();
    jtextDisplay.setText(iNumber);
    }//GEN-LAST:event_jbutton0ActionPerformed

    private void jbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton5ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton5.getText();
    jtextDisplay.setText(iNumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton5ActionPerformed

    private void jbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton2ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton2.getText();
    jtextDisplay.setText(iNumber);

    }//GEN-LAST:event_jbutton2ActionPerformed

    private void jbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton3ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton3.getText();
    jtextDisplay.setText(iNumber);

    }//GEN-LAST:event_jbutton3ActionPerformed

    private void jbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton6ActionPerformed
    String iNumber = jtextDisplay.getText() + jbutton6.getText();
    jtextDisplay.setText(iNumber);

    }//GEN-LAST:event_jbutton6ActionPerformed

    private void jbuttonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonBackspaceActionPerformed
    String backSpace = null;
    if(jtextDisplay.getText().length() > 0)
      {
        StringBuilder digitRemove = new StringBuilder(jtextDisplay.getText());
        digitRemove.deleteCharAt(jtextDisplay.getText().length() - 1);
        backSpace = digitRemove.toString();
        jtextDisplay.setText(backSpace);
    }//GEN-LAST:event_jbuttonBackspaceActionPerformed
      }
    private void jbuttonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonDotActionPerformed
    if (!jtextDisplay.getText().contains(".")){
        jtextDisplay.setText(jtextDisplay.getText() + jbuttonDot.getText());
    }//GEN-LAST:event_jbuttonDotActionPerformed
    }
    private void jbuttonPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonPlusMinusActionPerformed
    double operations = Double.parseDouble(String.valueOf
    (jtextDisplay.getText()));
     operations = operations * (-1);
     jtextDisplay.setText(String.valueOf(operations));
    }//GEN-LAST:event_jbuttonPlusMinusActionPerformed

    private void jbuttonlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonlogActionPerformed
    double operations = Double.parseDouble(String.valueOf
    (jtextDisplay.getText()));
    operations = Math.log(operations);
        jtextDisplay.setText(String.valueOf(operations));
    
    }//GEN-LAST:event_jbuttonlogActionPerformed

    private void jbuttonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSinActionPerformed
    double operations = Double.parseDouble(String.valueOf
    (jtextDisplay.getText()));
     double radians = Math.toRadians(operations);  
     operations = Math.sin(radians);
     jtextDisplay.setText(String.valueOf(operations));
   
    }//GEN-LAST:event_jbuttonSinActionPerformed

    private void jbuttonSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSinhActionPerformed
    double operations = Double.parseDouble(String.valueOf
    (jtextDisplay.getText()));
       
    operations = Math.sinh(operations);
    jtextDisplay.setText(String.valueOf(operations));
   
    }//GEN-LAST:event_jbuttonSinhActionPerformed

    private void jbuttonCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCoshActionPerformed
    double operations = Double.parseDouble(String.valueOf
    (jtextDisplay.getText()));
        
    operations = Math.cosh(operations);
        jtextDisplay.setText(String.valueOf(operations));
   
    }//GEN-LAST:event_jbuttonCoshActionPerformed

    private void jbuttonSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSubtractActionPerformed
    String subtract = jtextDisplay.getText();
    firstNumber = Double.parseDouble(subtract);
    characterOpreration = '-';
    jtextDisplay.setText("");   
    }//GEN-LAST:event_jbuttonSubtractActionPerformed

    private void jbuttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonPlusActionPerformed
    String plus = jtextDisplay.getText();
    firstNumber = Double.parseDouble(plus);
    characterOpreration = '+';
    jtextDisplay.setText("");
    }//GEN-LAST:event_jbuttonPlusActionPerformed

    private void jbuttonMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMultiplicationActionPerformed
    String Multiplication = jtextDisplay.getText();
    firstNumber = Double.parseDouble(Multiplication);
    characterOpreration = '*';
    jtextDisplay.setText("");

    }//GEN-LAST:event_jbuttonMultiplicationActionPerformed

    private void jbtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivisionActionPerformed
    String Division = jtextDisplay.getText();
    firstNumber = Double.parseDouble(Division);
    characterOpreration = '/';
    jtextDisplay.setText("");

    }//GEN-LAST:event_jbtnDivisionActionPerformed

    private void jbuttonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonEqualActionPerformed
    String displayCalculation = jtextDisplay.getText();
    secondNumber = Double.parseDouble(displayCalculation);
      if(characterOpreration =='+'){
        result = firstNumber + secondNumber;
        jtextDisplay.setText(String.valueOf(result));
    }//GEN-LAST:event_jbuttonEqualActionPerformed
      if(characterOpreration =='-'){
      result = firstNumber - secondNumber;
      jtextDisplay.setText(String.valueOf(result));
    }
      if(characterOpreration =='*'){
      result = firstNumber * secondNumber;
      jtextDisplay.setText(String.valueOf(result));
    }
      if(characterOpreration =='/'){
      result = firstNumber / secondNumber;
      jtextDisplay.setText(String.valueOf(result));
    }
      if(characterOpreration =='m'){
      result = firstNumber % secondNumber;
      jtextDisplay.setText(String.valueOf(result));
    }
    }
    private void jbuttonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCosActionPerformed
    double operations = Double.parseDouble(String.valueOf(jtextDisplay.getText()));
    double radians = Math.toRadians(operations);        
    operations = Math.cos(radians);
    jtextDisplay.setText(String.valueOf(operations));


    }//GEN-LAST:event_jbuttonCosActionPerformed

    private void jbuttonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonTanActionPerformed
    double operations = Double.parseDouble(String.valueOf(jtextDisplay.getText()));
    double radians = Math.toRadians(operations);      
    operations = Math.tan(radians);
    jtextDisplay.setText(String.valueOf(operations));


    }//GEN-LAST:event_jbuttonTanActionPerformed

    private void jbuttonTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonTanhActionPerformed
    double operations = Double.parseDouble(String.valueOf(jtextDisplay.getText()));
        
    operations = Math.tanh(operations);
    jtextDisplay.setText(String.valueOf(operations));
    }//GEN-LAST:event_jbuttonTanhActionPerformed
//To be completed
    private void jbuttonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonPiActionPerformed

        
    }//GEN-LAST:event_jbuttonPiActionPerformed

    private void jbuttonCbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCbrActionPerformed
    }//GEN-LAST:event_jbuttonCbrActionPerformed

    private void jbuttonRandomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonRandomNumberActionPerformed

    }//GEN-LAST:event_jbuttonRandomNumberActionPerformed

    private void jbuttonXSquaredYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonXSquaredYActionPerformed

    }//GEN-LAST:event_jbuttonXSquaredYActionPerformed

    private void jbuttonXSquared2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonXSquared2ActionPerformed
    }//GEN-LAST:event_jbuttonXSquared2ActionPerformed

    private void jbuttonXSquared3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonXSquared3ActionPerformed
    }//GEN-LAST:event_jbuttonXSquared3ActionPerformed

    private void jbuttonHexaDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonHexaDecimalActionPerformed
    }//GEN-LAST:event_jbuttonHexaDecimalActionPerformed

    private void jbuttonBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonBinaryActionPerformed
    }//GEN-LAST:event_jbuttonBinaryActionPerformed

    private void jbuttonOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonOctalActionPerformed
    }//GEN-LAST:event_jbuttonOctalActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jbuttonFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonFactorialActionPerformed
        
    }//GEN-LAST:event_jbuttonFactorialActionPerformed

    private void jbuttonModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonModulusActionPerformed
       
    }//GEN-LAST:event_jbuttonModulusActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton27;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton jbtnDivision;
    private javax.swing.JButton jbutton0;
    private javax.swing.JButton jbutton1;
    private javax.swing.JButton jbutton2;
    private javax.swing.JButton jbutton3;
    private javax.swing.JButton jbutton4;
    private javax.swing.JButton jbutton5;
    private javax.swing.JButton jbutton6;
    private javax.swing.JButton jbutton7;
    private javax.swing.JButton jbutton8;
    private javax.swing.JButton jbutton9;
    private javax.swing.JButton jbuttonBackspace;
    private javax.swing.JButton jbuttonBinary;
    private javax.swing.JButton jbuttonCbr;
    private javax.swing.JButton jbuttonClear;
    private javax.swing.JButton jbuttonCos;
    private javax.swing.JButton jbuttonCosh;
    private javax.swing.JButton jbuttonDot;
    private javax.swing.JButton jbuttonEqual;
    private javax.swing.JButton jbuttonFactorial;
    private javax.swing.JButton jbuttonHexaDecimal;
    private javax.swing.JButton jbuttonModulus;
    private javax.swing.JButton jbuttonMultiplication;
    private javax.swing.JButton jbuttonOctal;
    private javax.swing.JButton jbuttonPi;
    private javax.swing.JButton jbuttonPlus;
    private javax.swing.JButton jbuttonPlusMinus;
    private javax.swing.JButton jbuttonRandomNumber;
    private javax.swing.JButton jbuttonRoot;
    private javax.swing.JButton jbuttonSin;
    private javax.swing.JButton jbuttonSinh;
    private javax.swing.JButton jbuttonSubtract;
    private javax.swing.JButton jbuttonTan;
    private javax.swing.JButton jbuttonTanh;
    private javax.swing.JButton jbuttonXSquared2;
    private javax.swing.JButton jbuttonXSquared3;
    private javax.swing.JButton jbuttonXSquaredY;
    private javax.swing.JButton jbuttonlog;
    private javax.swing.JTextField jtextDisplay;
    // End of variables declaration//GEN-END:variables
}
